# Generated by Django 5.1.1 on 2024-12-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_income_budget_budgetsource_expensecategory_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
    ]
